name: Test execution
on: 
  push: 
    branches: 
      - actions
  workflow_dispatch: 
  
jobs: 
  Set-Up-Python:
    runs-on: ubuntu-latest
    steps: 
      - name: "install python"
      - run: echo "Hello world"